### ISSUE TITLE
404 error entering settings

### ISSUE THREAD

**Issue by ittomsk** [taktos/redmine_holidays_plugin#1]
When I go to /settings/plugin/redmine_holidays_plugin I receive 404

The page you were trying to access doesn't exist or has been removed.

**Comment by ittomsk** [comment]
I fixed it by doing this

cd REDMINE_ROOT/plugins
git clone https://github.com/taktos/redmine_holidays_plugin.git redmine_holidays_plugin
rake redmine:plugins:migrate RAILS_ENV=production
service apache2 restart

**Comment by taktos** [comment]
Thank you, @ittomsk ! I fixed installation instructions of README.
